### ISSUE TITLE
Migration from V2 to V3

### ISSUE THREAD

**Issue by philippfo9** [coreui/coreui-react#130]
There is no clear documentation on how to upgrade from Version 2 to Version 3 of CoreUI for React, esp. as we have been using 'reactstrap' directly before.

Are there any extensive migration documentations planned?

**Comment by woothu** [comment]
V2 and V3 are hugely different, so only manual migration is possible. V3 new components differ from reactstrap, so in this case also only manual migration is possible.

When it comes to template components migration, `coreui-free-react-admin-template` shows an example setup.

**Comment by philippfo9** [comment]
It's clear to me that only manual migration is possible, but there is no real migration guide for what to do

**Comment by Valoran** [comment]
My team is also looking to upgrade a fairly big project from V2 to V3, and some documentation would help immensely, otherwise we would have to go by the "upgrade and try to see what explodes" method, and I would prefer to avoid that.
If there is some migration documentation planned we can easily wait for it as there is no rush, but it would be nice to know if it's beeing worked on or not.
Thanks in advance!

**Comment by woothu** [comment]
Migration docs are now available:

https://github.com/coreui/coreui-free-react-admin-template/blob/master/migration.md
