### ISSUE TITLE
How evit close CSidebar?

### ISSUE THREAD

**Issue by andrestigre** [coreui/coreui-react#158]
I need to keep the CSideBar open,

I try

```
<CSidebar
        aside
        colorScheme='light'
        size='lg'
        show={sidebarState.asideShow}
        //onShowChange={handleClick} 
        className="wrapper"
        dropdownMode={"noAction"}
        overlaid={overlaidSide}
      >
        <CSidebarClose
          id={"closeAside"}
          onClick={handleClick}
        />
        <Tabsaside className="scrollbar" />
      </CSidebar>
```

but when I click outside the CSideBar it closes, how to prevent it from closing?

**Comment by xidedix** [comment]
fixed with @coreui/react `v3.3.1` 

There was a bug in CSidebar always closing for `overlaid` prop.

The default behavior for CSidebar with `overlaid` prop is to close CSidebar on backdrop click and Esc keydown.
If you pass `onShowChange` callback function like in template example, the default state passed triggers the same behavior as without onShowChange().
This is the point of entry where you can decide whether to change show prop of CSidebar to false or not.

Starting from v3.3.1, along with `overlaid` prop you can pass empty callback function `onShowChange={() => {}}` or put there some external logic to trigger (or not), state change of CSidebar `show` prop.
