### ISSUE TITLE
CSidebar - hides after zooming in and does not come back after setting standard zoom

### ISSUE THREAD

**Issue by klaseca** [coreui/coreui-react#312]
### Systems:

Ubuntu
- Version: 20.04
- Chrome Version 103.0.5060.134

Windows
- Version 10 Pro 21H2
- Chrome Version 103.0.5060.114

### Steps to repeat:

- Go to page - https://coreui.io/demos/react/4.3/dark/#/dashboard
- Zoom in on the page until the sidebar disappears
- Revert zoom to it is original state

**Expected**: Sidebar hides when zoomed in and returns when zoomed in to standard

**Actual**: Sidebar hides when zoomed in and not returns when zoomed in to standard

**Comment by mohyddintash** [comment]
Hi, I confirm the same problem. 

Another issue possibly related, is that after you increase the window size, the sidebar element gets the 'hide' css class added to it, which is why you have to click twice on the hamburger button to open it again.

I did some digging and it seems to be [this](https://github.com/coreui/coreui-react/blob/main/packages/coreui-react/src/components/sidebar/CSidebar.tsx#L101) part of the code.

```ts
useEffect(() => {
      mobile && visible && setVisible(false);
    }, [mobile])
```

making it as follows resolves both problems:

```ts
useEffect(() => {
      mobile && _visible && setVisible(false);
     !mobile && !_visible && setVisible(true);
    }, [mobile])
```

**Comment by KelvinTegelaar** [comment]
This also happens on high-resolution screens with a zoomed in DPI. e.g. 4k screens with 150% DPI.

**Comment by Lartza** [comment]
This is still an issue and seemingly solved by the single line edit above.
