### ISSUE TITLE
Upgrade to React Router 5

### ISSUE THREAD

**Issue by iansu** [coreui/coreui-react#67]
I see that you've locked React Router to `~4.3.1`. I'm curious why not just upgrade to React Router 5? I'm sure there's a good reason I'm just wondering what it is and what would be required to get React Router upgraded?

**Comment by xidedix** [comment]
Hi @iansu 
That's a kind of breaking change. With the upgrade to v5, you'll see an error message: `You should not render a <Route> outside a <Router>`. It means that `Route` can't find the correct context object because `Breadcrumb` and `SidebarNav` components have their own context object. 
We're working on a solution.

**Comment by iansu** [comment]
Right, I got that error and downgraded to `4.3.1`. I was just wondering why you can't easily upgrade. I'm happy to help with this if I can.

**Comment by iansu** [comment]
It seems like this was done in 2.5.0. However, that version isn't tagged as latest. This appears to be working though so I'll close this issue. Thanks!
